services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=$NGINX_HOST
    networks:
      - main
    restart: always

  api:
    build:
      context: ./api
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - INTRA_PROXY_ENDPOINT=${INTRA_PROXY_ENDPOINT}
      - INTRA_PROXY_SECRET=${INTRA_PROXY_SECRET}
      - MONGO_URI=${MONGO_URI}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - main
      - db
    restart: always
    image: bwisniew/intra-tutors-api:latest
  
  app:
    build:
      context: ./app
      args:
        REACT_APP_BACKEND_URL: ${BACKEND_URL}
    networks:
      - main
    restart: always
    image: bwisniew/intra-tutors-app:latest

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - db
    restart: always
    ports:
      - "27018:27017"

volumes:
  mongo-data:

networks:
  main:
    driver: bridge
  db:
    driver: bridge
